/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-03-01 14:57:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class toUserRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <title>用户注册</title>  \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"html/css/pintuer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"html/css/admin.css\">\r\n");
      out.write("    <script src=\"html/js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"html/js/pintuer.js\"></script> \r\n");
      out.write("\t<script>\r\n");
      out.write("\t function check(){\r\n");
      out.write("\t\t var p1 = document.getElementById(\"pwd\").value;\r\n");
      out.write("\t\t var p2 = document.getElementById(\"pwd_again\").value;\r\n");
      out.write("\t\t var cpw = document.getElementById(\"comfirm_pwd\");\r\n");
      out.write("\t\t if(p1==p2)\r\n");
      out.write("\t\t\t comfirm_pwd.innerHTML=\"<font  color='green'>密码一致</font>\";\r\n");
      out.write("\t\t else\r\n");
      out.write("\t\t\t comfirm_pwd.innerHTML=\"<font  color='red'>密码不同</font>\";\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t }\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("<div class=\"bg\"></div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"line bouncein\">\r\n");
      out.write("        <div class=\"xs6 xm4 xs3-move xm4-move\">\r\n");
      out.write("            <div style=\"height:150px;\"></div>\r\n");
      out.write("            <div class=\"media media-y margin-big-bottom\">           \r\n");
      out.write("            </div>         \r\n");
      out.write("            <form action=\"Register\" method=\"post\">\r\n");
      out.write("            <div class=\"panel loginbox\">\r\n");
      out.write("                <div class=\"text-center margin-big padding-big-top\"><h1>用户注册</h1></div>\r\n");
      out.write("                <div class=\"panel-body\" style=\"padding:30px; padding-bottom:10px; padding-top:10px;\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"field field-icon-right\">\r\n");
      out.write("                            <input type=\"text\" class=\"input input-big\"  id=\"userName\" name=\"userName\" placeholder=\"用户昵称\"  data-validate=\"required:请输入昵称\" />\r\n");
      out.write("                            <span class=\"icon icon-user margin-small\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"field field-icon-right\">\r\n");
      out.write("                            <input type=\"text\" id=\"用户电话\" class=\"input input-big\" name=\"phone\" placeholder=\"电话\" data-validate=\"required:请输入电话\" />\r\n");
      out.write("                            <span class=\"icon icon-key margin-small\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                   \r\n");
      out.write("\t\t\t\t\t <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"field field-icon-right\">\r\n");
      out.write("                            <input type=\"password\" id=\"pwd\" class=\"input input-big\" name=\"pwd\" placeholder=\"登陆密码\" data-validate=\"required:请输入密码\" />\r\n");
      out.write("                            <span class=\"icon icon-key margin-small\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"field field-icon-right\">\r\n");
      out.write("                            <input type=\"password\" id=\"pwd_again\" class=\"input input-big\" name=\"pwd\"  placeholder=\"确认密码\" onkeyup=\"check()\" />\r\n");
      out.write("                            <span id=\"comfirm_pwd\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"field field-icon-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p style=\"color:gray;font-size:16px\">性别：</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        <div class=\"field field-icon-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"m\"><span style=\"color:gray;font-size:15px\">男</span>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"w\"><span style=\"color:gray;font-size:15px\">女</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"padding:30px;\"><input type=\"submit\"   class=\"button button-block bg-main text-big input-big\" value=\"注册\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>          \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
