/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-06-03 15:03:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html_005f5;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("author: W3layouts\r\n");
      out.write("author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Grocery Store a Ecommerce Online Shopping Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>\r\n");
      out.write("<!-- for-mobile-apps -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Grocery Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("\t\tfunction hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- //for-mobile-apps -->\r\n");
      out.write("<link href=\"html_5/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"html_5/css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"html_5/css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" /> \r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"html_5/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<!-- //js -->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"html_5/js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"html_5/js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write(" function check(){\r\n");
      out.write("\t  var userName=\"");
      out.print(session.getAttribute("user"));
      out.write("\";\r\n");
      out.write("\t  var noLogin = document.getElementById(\"noLogin\");\r\n");
      out.write("\t  var haveLogin = document.getElementById(\"haveLogin\");\r\n");
      out.write("\t  var name = document.getElementById(\"userName\");\r\n");
      out.write("\t  if(\"null\"==userName){\r\n");
      out.write("\t\t  noLogin.hidden = false;\r\n");
      out.write("\t\t  haveLogin.hidden = true;\r\n");
      out.write("\t  }else{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    noLogin.hidden = true;\r\n");
      out.write("\t\t  haveLogin.hidden = false;\r\n");
      out.write("\t\t  name.innerHTML=userName+'  ';\r\n");
      out.write("\t  }\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function logout(){\r\n");
      out.write("window.location.href='html_5/logout.jsp';\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write(" }\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<body onload=\"check()\">\r\n");
      out.write("\r\n");
      out.write("<!--JSP--->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      out.write("\t<div class=\"agileits_header\">\r\n");
      out.write("\t\t<div class=\"w3l_offers\">\r\n");
      out.write("\t\t\t<a href=\"products.html\">Today's special Offers !</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_search\">\r\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"Product\" value=\"Search a product...\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Search a product...';}\" required=\"\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\" \">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"product_list_header\">  \r\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\" class=\"last\">\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <input type=\"hidden\" name=\"cmd\" value=\"_cart\" />\r\n");
      out.write("                    <input type=\"hidden\" name=\"display\" value=\"1\" />\r\n");
      out.write("                    <input type=\"submit\" name=\"submit\" value=\"View your cart\" class=\"button\" />\r\n");
      out.write("                </fieldset>\r\n");
      out.write("            </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"w3l_header_right\" id=\"noLogin\"  >\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t<li class=\"dropdown profile_details_drop\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t<i class=\"fa fa-user\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t<div class=\"mega-dropdown-menu\">\r\n");
      out.write("\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t<ul class=\"dropdown-menu drp-mnu\">\r\n");
      out.write("         <form action=\"toLogin\">\r\n");
      out.write("\t\t <li><input type=\"submit\" value=\"Login\"/></li> \r\n");
      out.write("\t     <li><input type=\"submit\" value=\"Register\"/></li>\r\n");
      out.write("\t   </form>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>               \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t</ul></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"w3l_header_right\" style=\"padding-left:50px\" id=\"haveLogin\" hidden=\"true\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t<li class=\"dropdown profile_details_drop\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t<i class=\"fa fa-user\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t<span id=\"userName\"></span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t \r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<a onclick=\"logout()\"   >logout</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("  \r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- script-for sticky-nav -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t var navoffeset=$(\".agileits_header\").offset().top;\r\n");
      out.write("\t\t $(window).scroll(function(){\r\n");
      out.write("\t\t\tvar scrollpos=$(window).scrollTop(); \r\n");
      out.write("\t\t\tif(scrollpos >=navoffeset){\r\n");
      out.write("\t\t\t\t$(\".agileits_header\").addClass(\"fixed\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\".agileits_header\").removeClass(\"fixed\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t \r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //script-for sticky-nav -->\r\n");
      out.write("\t<div class=\"logo_products\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"w3ls_logo_products_left\">\r\n");
      out.write("\t\t\t\t<h1><a href=\"index.html\"><span>Grocery</span> Store</a></h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3ls_logo_products_left1\">\r\n");
      out.write("\t\t\t\t<ul class=\"special_items\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"events.html\">Events</a><i>/</i></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.html\">About Us</a><i>/</i></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.html\">Best Deals</a><i>/</i></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3ls_logo_products_left1\">\r\n");
      out.write("\t\t\t\t<ul class=\"phone_email\">\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>(+0123) 234 567</li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i><a href=\"mailto:store@grocery.com\">store@grocery.com</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //header -->\r\n");
      out.write("<!-- banner -->\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("\t\t<div class=\"w3l_banner_nav_left\">\r\n");
      out.write("\t\t\t<nav class=\"navbar nav_bottom\">\r\n");
      out.write("\t\t\t <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t  <div class=\"navbar-header nav_2\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"navbar-toggle collapsed navbar-toggle1\" data-toggle=\"collapse\" data-target=\"#bs-megadropdown-tabs\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t  </button>\r\n");
      out.write("\t\t\t   </div> \r\n");
      out.write("\t\t\t   <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-megadropdown-tabs\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav nav_1\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"products.html\">Branded Foods</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"household.html\">Households</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown mega-dropdown active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Veggies & Fruits<span class=\"caret\"></span></a>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu mega-dropdown-menu w3ls_vegetables_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"vegetables.html\">Vegetables</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"vegetables.html\">Fruits</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"kitchen.html\">Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"short-codes.html\">Short Codes</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Beverages<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu mega-dropdown-menu w3ls_vegetables_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"drinks.html\">Soft Drinks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"drinks.html\">Juices</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pet.html\">Pet Food</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Frozen Foods<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu mega-dropdown-menu w3ls_vegetables_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"frozen.html\">Frozen Snacks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"frozen.html\">Frozen Nonveg</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"bread.html\">Bread & Bakery</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t </div><!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_banner_nav_right\">\r\n");
      out.write("\t\t\t<section class=\"slider\">\r\n");
      out.write("\t\t\t\t<div class=\"flexslider\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"slides\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3l_banner_nav_right_banner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Make your <span>food</span> with Spicy.</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"more\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"products.html\" class=\"button--saqui button--round-l button--text-thick\" data-text=\"Shop now\">Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3l_banner_nav_right_banner1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Make your <span>food</span> with Spicy.</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"more\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"products.html\" class=\"button--saqui button--round-l button--text-thick\" data-text=\"Shop now\">Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3l_banner_nav_right_banner2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>upto <i>50%</i> off.</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"more\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"products.html\" class=\"button--saqui button--round-l button--text-thick\" data-text=\"Shop now\">Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- flexSlider -->\r\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"css/flexslider.css\" type=\"text/css\" media=\"screen\" property=\"\" />\r\n");
      out.write("\t\t\t\t<script defer src=\"js/jquery.flexslider.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t$(window).load(function(){\r\n");
      out.write("\t\t\t\t  $('.flexslider').flexslider({\r\n");
      out.write("\t\t\t\t\tanimation: \"slide\",\r\n");
      out.write("\t\t\t\t\tstart: function(slider){\r\n");
      out.write("\t\t\t\t\t  $('body').removeClass('loading');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t  });\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t  </script>\r\n");
      out.write("\t\t\t<!-- //flexSlider -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- banner -->\r\n");
      out.write("\t<div class=\"banner_bottom\">\r\n");
      out.write("\t\t\t<div class=\"wthree_banner_bottom_left_grid_sub\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"wthree_banner_bottom_left_grid_sub1\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 wthree_banner_bottom_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_banner_bottom_left_grid\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/4.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wthree_banner_bottom_left_grid_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Discount Offer <span>25%</span></h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 wthree_banner_bottom_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_banner_bottom_left_grid\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/5.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wthree_banner_btm_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>introducing <span>best store</span> for <i>groceries</i></h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 wthree_banner_bottom_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wthree_banner_bottom_left_grid\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/6.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wthree_banner_btm_pos1\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Save <span>Upto</span> $10</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- top-brands -->\r\n");
      out.write("\t<div class=\"top-brands\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h3>Hot Offers</h3>\r\n");
      out.write("\t\t\t<div class=\"agile_top_brands_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 top_brand_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"hover14 column\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tag\"><img src=\"images/tag.png\" alt=\" \" class=\"img-responsive\" /></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"snipcart-item block\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"single.html\"><img title=\" \" alt=\" \" src=\"images/1.png\" /></a>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>fortune sunflower oil</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>$7.99 <span>$10.00</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-details top_brand_home_details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cmd\" value=\"_cart\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"add\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"business\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item_name\" value=\"Fortune Sunflower Oil\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"amount\" value=\"7.99\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"discount_amount\" value=\"1.00\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"currency_code\" value=\"USD\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"return\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cancel_return\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Add to cart\" class=\"button\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 top_brand_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"hover14 column\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"snipcart-item block\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"single.html\"><img title=\" \" alt=\" \" src=\"images/3.png\" /></a>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>basmati rise (5 Kg)</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>$11.99 <span>$15.00</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-details top_brand_home_details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cmd\" value=\"_cart\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"add\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"business\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item_name\" value=\"basmati rise\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"amount\" value=\"11.99\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"discount_amount\" value=\"1.00\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"currency_code\" value=\"USD\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"return\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cancel_return\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Add to cart\" class=\"button\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 top_brand_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"hover14 column\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/offer.png\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"snipcart-item block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/2.png\" alt=\" \" class=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Pepsi soft drink (2 Ltr)</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>$8.00 <span>$10.00</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-details top_brand_home_details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cmd\" value=\"_cart\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"add\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"business\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item_name\" value=\"Pepsi soft drink\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"amount\" value=\"8.00\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"discount_amount\" value=\"1.00\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"currency_code\" value=\"USD\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"return\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cancel_return\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Add to cart\" class=\"button\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 top_brand_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"hover14 column\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/offer.png\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"agile_top_brand_left_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figure>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"snipcart-item block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/4.png\" alt=\" \" class=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>dogs food (4 Kg)</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>$9.00 <span>$11.00</span></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"snipcart-details top_brand_home_details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cmd\" value=\"_cart\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"add\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"business\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item_name\" value=\"dogs food\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"amount\" value=\"9.00\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"discount_amount\" value=\"1.00\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"currency_code\" value=\"USD\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"return\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cancel_return\" value=\" \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Add to cart\" class=\"button\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //top-brands -->\r\n");
      out.write("<!-- fresh-vegetables -->\r\n");
      out.write("\t<div class=\"fresh-vegetables\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h3>Top Products</h3>\r\n");
      out.write("\t\t\t<div class=\"w3l_fresh_vegetables_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 w3l_fresh_vegetables_grid w3l_fresh_vegetables_grid_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3l_fresh_vegetables_grid2\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"products.html\">All Brands</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"vegetables.html\">Vegetables</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"vegetables.html\">Fruits</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"drinks.html\">Juices</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"pet.html\">Pet Food</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"bread.html\">Bread & Bakery</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"household.html\">Cleaning</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"products.html\">Spices</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"products.html\">Dry Fruits</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-check\" aria-hidden=\"true\"></i><a href=\"products.html\">Dairy Products</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 w3l_fresh_vegetables_grid_right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 w3l_fresh_vegetables_grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"w3l_fresh_vegetables_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/8.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 w3l_fresh_vegetables_grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"w3l_fresh_vegetables_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3l_fresh_vegetables_grid1_rel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/7.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3l_fresh_vegetables_grid1_rel_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"more m1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"products.html\" class=\"button--saqui button--round-l button--text-thick\" data-text=\"Shop now\">Shop now</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"w3l_fresh_vegetables_grid1_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/10.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3l_fresh_vegetables_grid1_bottom_pos\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>Special Offers</h5>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 w3l_fresh_vegetables_grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"w3l_fresh_vegetables_grid1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/9.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"w3l_fresh_vegetables_grid1_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/11.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"agileinfo_move_text\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agileinfo_marquee\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>get <span class=\"blink_me\">25% off</span> on first order and also get gift voucher</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agileinfo_breaking_news\">\r\n");
      out.write("\t\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //fresh-vegetables -->\r\n");
      out.write("<!-- newsletter -->\r\n");
      out.write("\t<div class=\"newsletter\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"w3agile_newsletter_left\">\r\n");
      out.write("\t\t\t\t<h3>sign up for our newsletter</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3agile_newsletter_right\">\r\n");
      out.write("\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" name=\"Email\" value=\"Email\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Email';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"subscribe now\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //newsletter -->\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>information</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"events.html\">Events</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.html\">Best Deals</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"short-codes.html\">Short Codes</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>policy info</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"faqs.html\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"privacy.html\">privacy policy</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"privacy.html\">terms of use</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>what in stores</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"pet.html\">Pet Food</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"frozen.html\">Frozen Snacks</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"kitchen.html\">Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.html\">Branded Foods</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"household.html\">Households</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>twitter posts</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list1\">\r\n");
      out.write("\t\t\t\t\t<li><label class=\"fa fa-twitter\" aria-hidden=\"true\"></label><i>01 day ago</i><span>Non numquam <a href=\"#\">http://sd.ds/13jklf#</a>\r\n");
      out.write("\t\t\t\t\t\teius modi tempora incidunt ut labore et\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">http://sd.ds/1389kjklf#</a>quo nulla.</span></li>\r\n");
      out.write("\t\t\t\t\t<li><label class=\"fa fa-twitter\" aria-hidden=\"true\"></label><i>02 day ago</i><span>Con numquam <a href=\"#\">http://fd.uf/56hfg#</a>\r\n");
      out.write("\t\t\t\t\t\teius modi tempora incidunt ut labore et\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">http://fd.uf/56hfg#</a>quo nulla.</span></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t<div class=\"agile_footer_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 w3_footer_grid agile_footer_grids_w3_footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_footer_grid_bottom\">\r\n");
      out.write("\t\t\t\t\t\t<h4>100% secure payments</h4>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/card.png\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 w3_footer_grid agile_footer_grids_w3_footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_footer_grid_bottom\">\r\n");
      out.write("\t\t\t\t\t\t<h5>connect with us</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"agileits_social_icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"dribbble\"><i class=\"fa fa-dribbble\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"wthree_footer_copy\">\r\n");
      out.write("\t\t\t\t<p>© 2016 Grocery Store. All rights reserved | Design by <a href=\"http://w3layouts.com/\">W3layouts</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //footer -->\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\".dropdown\").hover(            \r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideDown(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');        \r\n");
      out.write("        },\r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideUp(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');       \r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- here stars scrolling icon -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //here ends scrolling icon -->\r\n");
      out.write("<script src=\"js/minicart.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t// Mini Cart\r\n");
      out.write("\tpaypal.minicart.render({\r\n");
      out.write("\t\taction: '#'\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tif (~window.location.search.indexOf('reset=true')) {\r\n");
      out.write("\t\tpaypal.minicart.reset();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
