/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-06-03 15:04:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html_005f5;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Grocery Store a Ecommerce Online Shopping Category Flat Bootstrap Responsive Website Template | Sign In & Sign Up :: w3layouts</title>\r\n");
      out.write("<!-- for-mobile-apps -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Grocery Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("\t\tfunction hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- //for-mobile-apps -->\r\n");
      out.write("<link href=\"html_5/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"html_5/css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"html_5/css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" /> \r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"html_5/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"html_5/js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"html_5/js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t function check(){\r\n");
      out.write("\t\t var p1 = document.getElementById(\"pwd\").value;\r\n");
      out.write("\t\t var p2 = document.getElementById(\"pwd_again\").value;\r\n");
      out.write("\t\t var cpw = document.getElementById(\"comfirm_pwd\");\r\n");
      out.write("\t\t if(p1==p2)\r\n");
      out.write("\t\t\t cpw.innerHTML=\"<font  color='green'>密码一致</font>\";\r\n");
      out.write("\t\t else\r\n");
      out.write("\t\t\t cpw.innerHTML=\"<font  color='red'>密码不同</font>\";\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t function check_em(){\r\n");
      out.write("\t   var em = document.getElementById(\"Reg_email\").value;\r\n");
      out.write("\t   var em_div = document.getElementById(\"error_msg\");\r\n");
      out.write("\t   if(em.indexOf('@')!=-1 && em.indexOf('.')!=-1)\r\n");
      out.write("\t   em_div.innerHTML='';\r\n");
      out.write("\t   else\r\n");
      out.write("\t   em_div.innerHTML=\"<font  color='red'>邮箱格式错误</font>\";\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("\t<div class=\"agileits_header\">\r\n");
      out.write("\t\t<div class=\"w3l_offers\">\r\n");
      out.write("\t\t\t<a href=\"products.html\">Today's special Offers !</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_search\">\r\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"Product\" value=\"Search a product...\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Search a product...';}\" required=\"\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\" \">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"product_list_header\">  \r\n");
      out.write("\t\t\t<form action=\"#\" method=\"post\" class=\"last\">\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <input type=\"hidden\" name=\"cmd\" value=\"_cart\" />\r\n");
      out.write("                    <input type=\"hidden\" name=\"display\" value=\"1\" />\r\n");
      out.write("                    <input type=\"submit\" name=\"submit\" value=\"View your cart\" class=\"button\" />\r\n");
      out.write("                </fieldset>\r\n");
      out.write("            </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_header_right\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown profile_details_drop\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i><span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"mega-dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu drp-mnu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"login.html\">Login</a></li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"login.html\">Sign Up</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_header_right1\">\r\n");
      out.write("\t\t\t<h2><a href=\"mail.html\">Contact Us</a></h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- script-for sticky-nav -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t var navoffeset=$(\".agileits_header\").offset().top;\r\n");
      out.write("\t\t $(window).scroll(function(){\r\n");
      out.write("\t\t\tvar scrollpos=$(window).scrollTop(); \r\n");
      out.write("\t\t\tif(scrollpos >=navoffeset){\r\n");
      out.write("\t\t\t\t$(\".agileits_header\").addClass(\"fixed\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\".agileits_header\").removeClass(\"fixed\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t });\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //script-for sticky-nav -->\r\n");
      out.write("\t<div class=\"logo_products\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"w3ls_logo_products_left\">\r\n");
      out.write("\t\t\t\t<h1><a href=\"index.html\"><span>Grocery</span> Store</a></h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3ls_logo_products_left1\">\r\n");
      out.write("\t\t\t\t<ul class=\"special_items\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"events.html\">Events</a><i>/</i></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.html\">About Us</a><i>/</i></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.html\">Best Deals</a><i>/</i></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3ls_logo_products_left1\">\r\n");
      out.write("\t\t\t\t<ul class=\"phone_email\">\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>(+0123) 234 567</li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i><a href=\"mailto:store@grocery.com\">store@grocery.com</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //header -->\r\n");
      out.write("<!-- products-breadcrumb -->\r\n");
      out.write("\t<div class=\"products-breadcrumb\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><i class=\"fa fa-home\" aria-hidden=\"true\"></i><a href=\"index.html\">Home</a><span>|</span></li>\r\n");
      out.write("\t\t\t\t<li>Sign In & Sign Up</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //products-breadcrumb -->\r\n");
      out.write("<!-- banner -->\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("\t\t<div class=\"w3l_banner_nav_left\">\r\n");
      out.write("\t\t<nav class=\"navbar nav_bottom\">\r\n");
      out.write("\t\t\t <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t  <div class=\"navbar-header nav_2\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"navbar-toggle collapsed navbar-toggle1\" data-toggle=\"collapse\" data-target=\"#bs-megadropdown-tabs\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t  </button>\r\n");
      out.write("\t\t\t   </div> \r\n");
      out.write("\t\t\t   <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-megadropdown-tabs\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav nav_1\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"products.html\">Branded Foods</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"household.html\">Households</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown mega-dropdown active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Veggies & Fruits<span class=\"caret\"></span></a>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu mega-dropdown-menu w3ls_vegetables_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"vegetables.html\">Vegetables</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"vegetables.html\">Fruits</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"kitchen.html\">Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"short-codes.html\">Short Codes</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Beverages<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu mega-dropdown-menu w3ls_vegetables_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"drinks.html\">Soft Drinks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"drinks.html\">Juices</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pet.html\">Pet Food</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Frozen Foods<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu mega-dropdown-menu w3ls_vegetables_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"w3ls_vegetables\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"frozen.html\">Frozen Snacks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"frozen.html\">Frozen Nonveg</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>                  \r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"bread.html\">Bread & Bakery</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t </div><!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3l_banner_nav_right\">\r\n");
      out.write("<!-- login -->\r\n");
      out.write("\t\t<div class=\"w3_login\">\r\n");
      out.write("\t\t\t<h3>Sign In & Sign Up</h3>\r\n");
      out.write("\t\t\t<div class=\"w3_login_module\">\r\n");
      out.write("\t\t\t\t<div class=\"module form-module\">\r\n");
      out.write("\t\t\t\t  <div class=\"toggle\"><i class=\"fa fa-times fa-pencil\"></i>\r\n");
      out.write("\t\t\t\t\t<div class=\"tooltip\">Click Me</div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form\">\r\n");
      out.write("\t\t\t\t\t<h2>Login to your account</h2>\r\n");
      out.write("\t\t\t\t\t<form action=\"BussinessLogin\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t  <input type=\"text\"  id=\"account\" name=\"phone\" placeholder=\"Username\" required=\" \">\r\n");
      out.write("\t\t\t\t\t  <input type=\"password\" name=\"pwd\"  placeholder=\"Password\" required=\" \">\r\n");
      out.write("\t\t\t\t\t  <input type=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form\">\r\n");
      out.write("\t\t\t\t\t<h2>Create an account</h2>\r\n");
      out.write("\t\t\t\t\t<form action=\"Register\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t  <input type=\"text\" name=\"phone\" placeholder=\"phone\" required=\" \">\r\n");
      out.write("\t\t\t\t\t  <input type=\"password\" name=\"pwd\" id=\"pwd\" placeholder=\"Password\" required=\" \"  >\r\n");
      out.write("\t\t\t\t\t  <div float=\"right\">\r\n");
      out.write("\t\t\t\t\t  <input type=\"password\" name=\"pwd\" id=\"pwd_again\" placeholder=\"Affirm Password\" onkeyup=\"check()\" required=\" \">\r\n");
      out.write("\t\t\t\t\t  </div><div><span id=\"comfirm_pwd\"></span></div>\r\n");
      out.write("\t\t\t\t\t  <input type=\"email\" name=\"email\" id=\"Reg_email\" placeholder=\"Email Address\" onkeyup=\"check_em()\" required=\" \">\r\n");
      out.write("\t\t\t\t\t  <span id=\"error_msg\"></span>\r\n");
      out.write("\t\t\t\t\t  <input type=\"submit\" value=\"Register\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"cta\"><a href=\"#\">Forgot your password?</a></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\t$('.toggle').click(function(){\r\n");
      out.write("\t\t\t\t  // Switches the Icon\r\n");
      out.write("\t\t\t\t  $(this).children('i').toggleClass('fa-pencil');\r\n");
      out.write("\t\t\t\t  // Switches the forms  \r\n");
      out.write("\t\t\t\t  $('.form').animate({\r\n");
      out.write("\t\t\t\t\theight: \"toggle\",\r\n");
      out.write("\t\t\t\t\t'padding-top': 'toggle',\r\n");
      out.write("\t\t\t\t\t'padding-bottom': 'toggle',\r\n");
      out.write("\t\t\t\t\topacity: \"toggle\"\r\n");
      out.write("\t\t\t\t  }, \"slow\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- //login -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //banner -->\r\n");
      out.write("<!-- newsletter-top-serv-btm -->\r\n");
      out.write("\t<div class=\"newsletter-top-serv-btm\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4 wthree_news_top_serv_btm_grid\">\r\n");
      out.write("\t\t\t\t<div class=\"wthree_news_top_serv_btm_grid_icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-shopping-cart\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>Nam libero tempore</h3>\r\n");
      out.write("\t\t\t\t<p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus \r\n");
      out.write("\t\t\t\t\tsaepe eveniet ut et voluptates repudiandae sint et.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 wthree_news_top_serv_btm_grid\">\r\n");
      out.write("\t\t\t\t<div class=\"wthree_news_top_serv_btm_grid_icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-bar-chart\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>officiis debitis aut rerum</h3>\r\n");
      out.write("\t\t\t\t<p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus \r\n");
      out.write("\t\t\t\t\tsaepe eveniet ut et voluptates repudiandae sint et.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 wthree_news_top_serv_btm_grid\">\r\n");
      out.write("\t\t\t\t<div class=\"wthree_news_top_serv_btm_grid_icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-truck\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>eveniet ut et voluptates</h3>\r\n");
      out.write("\t\t\t\t<p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus \r\n");
      out.write("\t\t\t\t\tsaepe eveniet ut et voluptates repudiandae sint et.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //newsletter-top-serv-btm -->\r\n");
      out.write("<!-- newsletter -->\r\n");
      out.write("\t<div class=\"newsletter\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"w3agile_newsletter_left\">\r\n");
      out.write("\t\t\t\t<h3>sign up for our newsletter</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3agile_newsletter_right\">\r\n");
      out.write("\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" name=\"Email\" value=\"Email\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Email';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"subscribe now\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //newsletter -->\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>information</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"events.html\">Events</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.html\">Best Deals</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"short-codes.html\">Short Codes</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>policy info</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"faqs.html\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"privacy.html\">privacy policy</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"privacy.html\">terms of use</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>what in stores</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"pet.html\">Pet Food</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"frozen.html\">Frozen Snacks</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"kitchen.html\">Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"products.html\">Branded Foods</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"household.html\">Households</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 w3_footer_grid\">\r\n");
      out.write("\t\t\t\t<h3>twitter posts</h3>\r\n");
      out.write("\t\t\t\t<ul class=\"w3_footer_grid_list1\">\r\n");
      out.write("\t\t\t\t\t<li><label class=\"fa fa-twitter\" aria-hidden=\"true\"></label><i>01 day ago</i><span>Non numquam <a href=\"#\">http://sd.ds/13jklf#</a>\r\n");
      out.write("\t\t\t\t\t\teius modi tempora incidunt ut labore et\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">http://sd.ds/1389kjklf#</a>quo nulla.</span></li>\r\n");
      out.write("\t\t\t\t\t<li><label class=\"fa fa-twitter\" aria-hidden=\"true\"></label><i>02 day ago</i><span>Con numquam <a href=\"#\">http://fd.uf/56hfg#</a>\r\n");
      out.write("\t\t\t\t\t\teius modi tempora incidunt ut labore et\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">http://fd.uf/56hfg#</a>quo nulla.</span></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t<div class=\"agile_footer_grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 w3_footer_grid agile_footer_grids_w3_footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_footer_grid_bottom\">\r\n");
      out.write("\t\t\t\t\t\t<h4>100% secure payments</h4>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/card.png\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 w3_footer_grid agile_footer_grids_w3_footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3_footer_grid_bottom\">\r\n");
      out.write("\t\t\t\t\t\t<h5>connect with us</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"agileits_social_icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"dribbble\"><i class=\"fa fa-dribbble\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"wthree_footer_copy\">\r\n");
      out.write("\t\t\t\t<p>© 2016 Grocery Store. All rights reserved | Design by <a href=\"http://w3layouts.com/\">W3layouts</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //footer -->\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\".dropdown\").hover(            \r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideDown(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');        \r\n");
      out.write("        },\r\n");
      out.write("        function() {\r\n");
      out.write("            $('.dropdown-menu', this).stop( true, true ).slideUp(\"fast\");\r\n");
      out.write("            $(this).toggleClass('open');       \r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- here stars scrolling icon -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- //here ends scrolling icon -->\r\n");
      out.write("<script src=\"js/minicart.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t// Mini Cart\r\n");
      out.write("\tpaypal.minicart.render({\r\n");
      out.write("\t\taction: '#'\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tif (~window.location.search.indexOf('reset=true')) {\r\n");
      out.write("\t\tpaypal.minicart.reset();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
